name: (KeyRotation) IAM <-> GitHub Action

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_IAM_USER_NAME:
        required: true
      GH_ACCESS_TOKEN:
        required: true
      SENTRY_DSN:
        required: true
      SLACK_BOT_TOKEN:
        required: false

env:
  APP_ENV: production
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_IAM_USER_NAME: ${{ secrets.AWS_IAM_USER_NAME }}
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  KR_IAM_GA_SERVICED_REPOS: ${{ vars.KR_IAM_GA_SERVICED_REPOS }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_ALERT_CHANNEL_ID: ${{ vars.SLACK_ALERT_CHANNEL_ID }}
  SLACK_NOTIFICATION_CHANNEL_ID: ${{ vars.SLACK_NOTIFICATION_CHANNEL_ID }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  WORKFLOW_ENVIRONMENT: ${{ inputs.environment }}

jobs:
  iam_github_action:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking-out remote scripts
        uses: actions/checkout@v3
        with:
          repository: oshopgiri/ops_bot
          ref: main
          path: ./
      - name: Setting-up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rotating keys
        run: ruby ./bin/key_rotation/iam_github_action.rb
